Completed css-brochure-form
ayshahussain141/rc1022-code-solutions pull request #15
Opened 2022-10-13 01:51 UTC by ayshahussain141

<img width="353" alt="css-page" src="https://user-images.githubusercontent.com/46547520/195480167-65ee5cfe-e477-4cd6-bd52-007bdc6e86c1.png">

2022-10-13 15:59 UTC, Zhiwutian requested changes
there are two changes I would make for this one: 
1. Make sure all of your fonts have a backup font assigned to them
2.  I would wrap the title and form in a main element, then set a width on that element of around 600px, then I would add css to that main element of margin: 0 auto which takes the available margin and divides it evenly around the element that should center the main container on the screen. Its much better than using margin to position the elements away from the left of the screen. 
Great work so far!

2022-10-13 15:59 UTC, Zhiwutian commented on css-brochure-form/styles.css
> +  font-family: AtlasGrotesk;
make sure you include a backup font for all fonts you use.

2022-10-14 00:10 UTC, ayshahussain141 commented
<img width="417" alt="Screenshot 2022-10-13 200829" src="https://user-images.githubusercontent.com/46547520/195733902-fb1ff804-5fa1-4eab-9410-36970a7db82d.png">

2022-10-14 15:32 UTC, Zhiwutian approved these changes
👍🏼

2022-10-17 00:01 UTC, merged