Completed css-two-column-layout
ayshahussain141/rc1022-code-solutions pull request #20
Opened 2022-10-14 23:13 UTC by ayshahussain141

<img width="472" alt="column-layout-two" src="https://user-images.githubusercontent.com/46547520/195956399-d148cb17-0451-4a5d-a8fd-3e8f9f10bd12.png">

2022-10-14 23:27 UTC, Zhiwutian requested changes
Hey Aysha, the look is very close to the example, but we do want to make some changes to the code structure to improve it. Let me know if you have any questions on the feedback. Good work so far!

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/index.html
> +  </div>
make sure all of these closing tags have an opening tag

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/styles.css
> +.column-one-fourth {
a column one fourth should have a flex basis of 25%
you also don't want to set width and flex basis together, because the width here will override the flex basis

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/styles.css
> +  margin-left: -150px;
you want to avoid using large amounts of margin like this. Margin should only be used for creating space between elements, not to position them

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/styles.css
> +  margin-right: 100px;
lots of margin being used here too, I would look for another way to get the elements where you want.

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/index.html
> +      <div class="column-one-fourth">
these two columns are very different in size, so it would be best to choose a column name which represents the amount of space you want them to take up.

2022-10-14 23:27 UTC, Zhiwutian commented on css-two-column-layout/index.html
> +      </div>
I would recommend wrapping each group of these columns in a `column-half` class set to 50% flex basis, then you can use display flex on the column half to control the sub columns. the sub columns should be more like 1/3 and 2/3s

2022-10-15 22:44 UTC, ayshahussain141 commented
<img width="502" alt="layout 2 0" src="https://user-images.githubusercontent.com/46547520/196010247-a522ff75-d7a9-4777-971e-a07ecabcc6d6.png">

2022-10-17 15:34 UTC, Zhiwutian approved these changes
Great work Aysha!

2022-10-17 17:03 UTC, merged