Completed html-tables
ayshahussain141/rc1022-code-solutions pull request #8
Opened 2022-10-11 23:14 UTC by ayshahussain141

<img width="229" alt="Screenshot 2022-10-11 191419" src="https://user-images.githubusercontent.com/46547520/195215151-c4271629-3c04-4bbd-b33b-b424ce4a9e19.png">

2022-10-11 23:18 UTC, Zhiwutian requested changes
a couple small updates

2022-10-11 23:18 UTC, Zhiwutian commented on html-tables/index.html
> +    <table>
don't forget to add the `thead` and `tbody` elements in the proper places

2022-10-11 23:18 UTC, Zhiwutian commented on html-tables/index.html
> +      <tr><th>Student Name</th><th>Course</th><th>Grade</th></tr>
I would separate this line into multiple lines for clarity purposes

2022-10-11 23:56 UTC, ayshahussain141 commented
<img width="245" alt="Screenshot 2022-10-11 195618 2 o" src="https://user-images.githubusercontent.com/46547520/195219241-05930d50-1993-4ab0-ba42-c96a20d1656f.png">

2022-10-12 00:02 UTC, Zhiwutian approved these changes
👍🏼

2022-10-12 15:43 UTC, merged